// spa/angular/src/app/components/nav-item/nav-item.component.ts
import { Component, Input } from '@angular/core';
import { MgnlContent } from '@magnolia/frontend-helpers-base';
import { environment } from '../../../environments/environment';
import { NavLinkComponent } from '../nav-link/nav-link.component';

@Component({
  selector: 'app-nav-item',
  standalone: true,
  imports: [NavLinkComponent],
  templateUrl: './nav-item.component.html',
})
export class NavItemComponent {
  @Input() content?: MgnlContent;
  @Input() nodeName!: string;
  @Input() currentLanguage!: string;
  @Input() isMagnoliaEdit = false;

  get path() {
    const baseName =
      this.currentLanguage === environment.languages[0]
        ? ''
        : '/' + this.currentLanguage;
    return (
      baseName + this.content?.['@path'].replace(this.nodeName || '', '') || '/'
    );
  }

  get subItems() {
    return (
      this.content?.['@nodes']?.map((nodeName) => {
        return this.content?.[nodeName] as MgnlContent;
      }) || []
    );
  }
}

@if (content) {
  <app-nav-link
    [path]="path"
    [isMagnoliaEdit]="isMagnoliaEdit"
    className="navbar-item"
  >
    {{ content['navigationTitle'] || content['title'] || content['@name'] }}
  </app-nav-link>

  @for (item of subItems; track item['@name']) {
    <app-nav-item
      class="space-x-6"
      [content]="item"
      [nodeName]="nodeName"
      [currentLanguage]="currentLanguage"
      [isMagnoliaEdit]="isMagnoliaEdit"
    ></app-nav-item>
  }
}

// spa/react/src/app/components/NavItem.jsx
import PropTypes from 'prop-types';
import { environment } from '../../environments/environment';
import NavLink from './NavLink';

const NavItem = ({ content, nodeName, currentLanguage, isMagnoliaEdit }) => {
  const baseName =
    currentLanguage === environment.languages[0] ? '' : '/' + currentLanguage;

  if (!content) {
    return null;
  }

  const children = content['@nodes']?.map((name) => (
    <NavItem
      key={name}
      content={content[name]}
      nodeName={nodeName}
      currentLanguage={currentLanguage}
      isMagnoliaEdit={isMagnoliaEdit}
    />
  ));

  return (
    <>
      <NavLink
        className='navbar-item'
        path={baseName + content['@path'].replace(nodeName || '', '') || '/'}
        isMagnoliaEdit={isMagnoliaEdit}
      >
        {content.navigationTitle || content.title || content['@name']}
      </NavLink>
      {children}
    </>
  );
};

NavItem.propTypes = {
  nodeName: PropTypes.string,
  content: PropTypes.object,
  currentLanguage: PropTypes.string,
  isMagnoliaEdit: PropTypes.bool,
};

export default NavItem;
