// spa/react/src/app/templates/pages/Basic.jsx
import { EditableArea } from '@magnolia/react-editor';
import PropTypes from 'prop-types';
import Footer from '../fragments/Footer';

const Basic = ({ main, footer }) => {
  return (
    <div className='flex flex-col justify-between min-h-[calc(100vh-5rem)]'>
      {main && <EditableArea content={main} />}
      {footer && <EditableArea content={footer} customView={Footer} />}
    </div>
  );
};

Basic.propTypes = {
  main: PropTypes.object,
  footer: PropTypes.object,
};

export default Basic;

// spa/angular/src/app/templates/pages/basic/basic.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { EditableArea } from '@magnolia/angular-editor';
import { MgnlContent } from '@magnolia/frontend-helpers-base';
import { FooterComponent } from '../../fragments/footer/footer.component';
import { NewsletterComponent } from '../../fragments/newsletter/newsletter.component';
import { FooterBottomComponent } from '../../fragments/footerBottom/footerBottom.component';
import { FeatureCardsComponent } from '../../components/featureCards/featureCards.component';
import { SectionTitleComponent } from '../../components/sectionTitle/sectionTitle.component';
import { HomeHeader } from '../../components/headerHome/headerHome.component';
import { FundingComponent } from '../../components/funding/funding.component';

@Component({
  templateUrl: './basic.component.html',
  standalone: true,
  imports: [EditableArea, FooterComponent, NewsletterComponent, FooterBottomComponent, FeatureCardsComponent, SectionTitleComponent, HomeHeader, FundingComponent],
})
export class BasicComponent {
  @Input() header!: MgnlContent;
  @Input() main!: MgnlContent;
  @Input() footer!: MgnlContent;
}


<div class="flex flex-col justify-between min-h-[calc(100vh-25rem)]">
  <header>
    <editable-area [content]="header"></editable-area>
  </header>
  <main>
    <editable-area [content]="main"></editable-area>

  </main>
  <app-funding></app-funding>
  <div editable-area [content]="footer" [customView]="renderFooter"></div>

</div>
<ng-template #renderFooter let-components="components">
  <app-newsletter [components]="components"></app-newsletter>
  <app-footer [components]="components"></app-footer>
  <app-footer-bottom [components]="components"></app-footer-bottom>
</ng-template>
