// spa/angular/src/app/templates/fragments/footerBottom/footerBottom.component.ts
import { Component, Input } from '@angular/core';
import { EditableComponent } from '@magnolia/angular-editor';
import { MgnlContent } from '@magnolia/frontend-helpers-base';

@Component({
  selector: 'app-footer-bottom',
  templateUrl: './footerBottom.component.html',
  standalone: true,
  imports: [EditableComponent],
})
export class FooterBottomComponent {
  @Input() components!: MgnlContent[];
}

<section class="p-2.5 bg-[#161a1d]">
  <div class="max-w-container mx-auto">
    <div class="flex">
      <div class="float-left">
        <p class="text-[#8c8c8c] m-0 text-xs">
          <a class="text-[#c33b32] no-underline" href="/page/site/public/english/UOBKH_terms.htm" target="_blank"><u>Terms &amp; Conditions</u></a> | 
          <a class="text-[#c33b32] no-underline" href="/page/site/public/english/pdf/UOBKH_PrivacyPolicy.pdf" target="_blank"><u>Privacy Policy</u></a> | 
          Copyright ©2018 UOB Kay Hian Pte Ltd. All rights reserved. Company Registration number 197000447W. Market data and news provided by 
          <img class="inline" src="/sgu_reuterslogoblack.gif" width="83" height="20" align="absbottom">
        </p>
      </div>
    </div>
  </div>
</section>

// spa/react/src/app/templates/fragments/FooterBottom.jsx
const FooterBottom = () => {
  return (
    <section className="p-2.5 bg-[#161a1d]">
      <div className="max-w-container mx-auto">
        <div className="flex">
          <div className="float-left">
            <p className="text-[#8c8c8c] m-0 text-xs">
              <a className="text-[#c33b32] no-underline" href="/page/site/public/english/UOBKH_terms.htm" target="_blank"><u>Terms &amp; Conditions</u></a> | 
              <a className="text-[#c33b32] no-underline" href="/page/site/public/english/pdf/UOBKH_PrivacyPolicy.pdf" target="_blank"><u>Privacy Policy</u></a> | 
              Copyright &copy;2018 UOB Kay Hian Pte Ltd. All rights reserved. Company Registration number 197000447W. Market data and news provided by 
              <img className="inline" src="/sgu_reuterslogoblack.gif" width="83" height="20" align="absbottom" alt="" />
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}
export default FooterBottom;
