// spa/angular/src/app/templates/components/list/list.component.ts
import { Component, Input } from '@angular/core';
import { EditableArea, EditableComponent } from '@magnolia/angular-editor';
import { MgnlContent } from '@magnolia/frontend-helpers-base';

@Component({
  templateUrl: './list.component.html',
  standalone: true,
  imports: [EditableArea, EditableComponent],
})
export class ListComponent {
  @Input() title!: string;
  @Input() theme!: string;
  @Input() items!: MgnlContent;

  get components() {
    return (
      (this.items?.['@nodes']?.map((nodeName) => {
        return this.items[nodeName];
      }) as MgnlContent[]) || []
    );
  }
}

<div class="px-8 py-6" [class]="{ 'bg-dark-teal': theme === 'dark' }">
  <p
    class="pb-4"
    [class]="{
      'text-light-green': theme === 'dark',
      'text-dark-teal': theme === 'light',
    }"
  >
    {{ title }}
  </p>

  @if (items) {
    <editable-area [content]="items" class="space-y-2" elementType="ul">
      @for (component of components; track component['@path']) {
        <li>
          <editable-component [content]="component"></editable-component>
        </li>
      }
    </editable-area>
  }
</div>

// spa/react/src/app/templates/components/List.jsx
import {
  ComponentHelper,
  EditableArea,
  EditableComponent,
} from '@magnolia/react-editor';
import PropTypes from 'prop-types';

const List = ({ title, theme, items }) => {
  const getComponents = () => {
    return (
      items?.['@nodes']?.map((nodeName) => {
        return items[nodeName];
      }) || []
    );
  };
  return (
    <div
      className={ComponentHelper.classnames([
        'px-8',
        'py-6',
        { 'bg-dark-teal': theme === 'dark' },
      ])}
    >
      <p
        className={ComponentHelper.classnames([
          'pb-4',
          {
            'text-light-green': theme === 'dark',
            'text-dark-teal': theme === 'light',
          },
        ])}
      >
        {title}
      </p>
      {items && (
        <EditableArea content={items} elementType='ul' className='space-y-2'>
          {getComponents().map((component) => {
            return (
              <li key={component['@name']}>
                <EditableComponent content={component} />
              </li>
            );
          })}
        </EditableArea>
      )}
    </div>
  );
};

List.propTypes = {
  title: PropTypes.string,
  theme: PropTypes.string,
  items: PropTypes.object,
};

export default List;
