// spa/react/src/app/templates/fragments/Image.jsx
import PropTypes from 'prop-types';
import { environment } from '../../../environments/environment';

const Image = ({ image, alt, caption }) => {
  if (image) {
    const damURL = `${environment.damRawBase}${image['@link']}`;
    return (
      <div>
        <img src={damURL} alt={alt} />
        {caption && <div className='text-center'>{caption}</div>}
      </div>
    );
  }
  return null;
};

Image.propTypes = {
  image: PropTypes.object,
  alt: PropTypes.string,
  caption: PropTypes.string,
};

export default Image;

// spa/angular/src/app/templates/fragments/image/image.component.ts
import { Component, Input } from '@angular/core';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-image',
  templateUrl: './image.component.html',
  standalone: true,
})
export class ImageComponent {
  @Input() caption!: string;
  @Input() image!: Record<string, unknown>;
  @Input() altText!: string;

  get damURL() {
    return environment.damRawBase + this.image?.['@link'];
  }
}

<div>
  <img src="{{ damURL }}" alt="{{ altText }}" />
  @if (caption) {
    <div class="text-center">{{ caption }}</div>
  }
</div>
