// spa/react/src/app/templates/pages/General.jsx
import { EditableArea } from '@magnolia/react-editor';
import PropTypes from 'prop-types';
import Footer from '../fragments/Footer';
import FooterBottom from '../fragments/FooterBottom';
import Newsletter from '../fragments/Newsletter';
import Header from '../components/Header';

const General = ({ main, footer }) => {
  return (
    <>
      <Header />
      <div className='flex flex-col justify-between min-h-[calc(100vh-25rem)]'>
        {main && <EditableArea content={main} />}
        
      </div>
      <Newsletter />
      <Footer />
      <FooterBottom />
    </>
  );
};

General.propTypes = {
  main: PropTypes.object,
  footer: PropTypes.object,
};

export default General;

// spa/angular/src/app/templates/pages/general/general.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { EditableArea } from '@magnolia/angular-editor';
import { MgnlContent } from '@magnolia/frontend-helpers-base';
import { FooterComponent } from '../../fragments/footer/footer.component';
import { FooterBottomComponent } from '../../fragments/footerBottom/footerBottom.component';
import { NewsletterComponent } from '../../fragments/newsletter/newsletter.component';
import { HomeHeader } from '../../components/headerHome/headerHome.component';
import { FundingComponent } from '../../components/funding/funding.component';

@Component({
  templateUrl: './general.component.html',
  standalone: true,
  imports: [EditableArea, HomeHeader, FooterComponent, FooterBottomComponent, NewsletterComponent, FundingComponent],
})
export class GeneralComponent {
  @Input() main!: MgnlContent;
}


<div class="">
  <app-home-header></app-home-header>
  <main class="flex flex-col justify-between min-h-[calc(100vh-25rem)]">
    <editable-area [content]="main"></editable-area>
  </main>
  
</div>

<app-newsletter></app-newsletter>

<app-footer></app-footer>
<app-footer-bottom></app-footer-bottom>
